
export const messagesData = [
	{
		text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse porta, sem sed viverra consequat, metus nunc dignissim dolor, sed volutpat erat ipsum volutpat erat.',
		timeCreated: Date.now() - 2000000,
		uid: 2,
		messageId: 1,	
	},
	{
		text: 'Cras congue eu tellus nec hendrerit. Pellentesque accumsan risus sit amet felis viverra dictum. Ut leo nisi, luctus ut hendrerit quis, vehicula quis velit. Sed id massa sit amet est vestibulum efficitur in in sapien. Aliquam erat volutpat. Donec tempor est eget dolor feugiat, a dignissim arcu dictum.',
		timeCreated: Date.now() - 1998000,
		uid: 1,
		messageId: 2,
		isDevided: true,
		chatBorderOrder: 1,
	},
	{
		text: 'Ut aliquam lectus augue, eget commodo nibh pulvinar eget. Suspendisse sagittis pellentesque magna, at tincidunt ex mollis in. ',

		timeCreated: Date.now()- 1998000,
		messageId: 3,
		uid: 1,
		chatBorderOrder: 3,
	},
	{
		text: 'Proin consectetur tortor et enim vulputate, et fringilla lorem cursus. Fusce congue mattis tortor quis tincidunt. Ut tincidunt magna ac blandit rhoncus.',
		timeCreated: Date.now() - 1900000,
		uid: 2,
		messageId: 4,
		isDevided: true,
	},
	{
		text: 'Vestibulum nec nibh mattis, posuere turpis ac, mattis elit. Praesent volutpat ac eros id rhoncus. Nam iaculis hendrerit magna ut efficitur.',
		timeCreated: Date.now() - 60000,
		uid: 2,
		messageId: 5,
		isDevided: true,
		isTimeStamped: true,
		chatBorderOrder: 1,
	},
	{
		text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse porta, sem sed viverra consequat, metus nunc dignissim dolor, sed volutpat erat ipsum volutpat erat.',
		timeCreated: Date.now() -50000,
		uid: 2,
		messageId: 6,
		chatBorderOrder: 3,
	},
	{
		text: 'Cras congue eu tellus nec hendrerit. Pellentesque accumsan risus sit amet felis viverra dictum. Ut leo nisi, luctus ut hendrerit quis, vehicula quis velit. Sed id massa sit amet est vestibulum efficitur in in sapien. Aliquam erat volutpat. Donec tempor est eget dolor feugiat, a dignissim arcu dictum.',
		timeCreated: Date.now() -50000,
		uid: 1,
		messageId: 7,
		isDevided: true,
		chatBorderOrder: 1,
	},
	{
		text: 'Ut aliquam lectus augue, eget commodo nibh pulvinar eget. Suspendisse sagittis pellentesque magna, at tincidunt ex mollis in. ',
		timeCreated: Date.now() -40000,
		uid: 1,
		messageId: 8,
		chatBorderOrder: 3,
	},
	{
		text: 'Proin consectetur tortor et enim vulputate, et fringilla lorem cursus. Fusce congue mattis tortor quis tincidunt. Ut tincidunt magna ac blandit rhoncus.',
		timeCreated: Date.now() -40000,
		uid: 2,
		messageId: 9,
		isDevided: true,
	},
	{
		text: 'Vestibulum nec nibh mattis, posuere turpis ac, mattis elit. Praesent volutpat ac eros id rhoncus. Nam iaculis hendrerit magna ut efficitur.',
		timeCreated: Date.now() -40000,
		uid: 1,
		messageId: 10,
		isDevided: true,
	},
];
